const clauses=window.CCT_CLAUSES||[];
const search=document.getElementById('search'),list=document.getElementById('list'),filters=document.getElementById('filters'),count=document.getElementById('count');
let current='Todas';const categories=['Todas',...new Set(clauses.map(c=>c.category))];
const plain=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function renderFilters(){filters.replaceChildren();for(const name of categories){const b=document.createElement('button');b.className='filter'+(name===current?' active':'');b.textContent=name;b.type='button';b.onclick=()=>{current=name;renderFilters();render()};filters.append(b)}}
function render(){const q=plain(search.value.trim());const rows=clauses.filter(c=>(current==='Todas'||c.category===current)&&plain(`${c.number} ${c.title} ${c.text}`).includes(q));count.textContent=`${rows.length} de ${clauses.length}`;list.replaceChildren();if(!rows.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='Nenhuma cláusula encontrada. Tente outra palavra ou escolha outro filtro.';list.append(empty);return}for(const c of rows){const d=document.createElement('details');d.className='clause';d.id=`clause-${c.number}`;const summary=document.createElement('summary');summary.innerHTML=`<div class="row"><span class="num">${c.number}</span><div><div class="ctitle">${esc(c.title)}</div><span class="cat">${esc(c.category)}</span></div></div>`;const body=document.createElement('div');body.className='content';const text=document.createElement('div');text.textContent=c.text;const actions=document.createElement('div');actions.className='actions';const share=document.createElement('button');share.type='button';share.className='btn';share.textContent='Compartilhar cláusula';share.onclick=async()=>{const url=location.href.split('#')[0]+'#clause-'+c.number;try{if(navigator.share)await navigator.share({title:`Cláusula ${c.number}ª – ${c.title}`,url});else{await navigator.clipboard.writeText(url);share.textContent='Link copiado'}}catch(e){}};const pdf=document.createElement('a');pdf.className='btn';pdf.href='CCT 2026 FINALIZADA.pdf';pdf.target='_blank';pdf.rel='noopener';pdf.textContent='Conferir PDF';actions.append(share,pdf);body.append(text,actions);d.append(summary,body);list.append(d)}}
function openClause(n){search.value='';current='Todas';renderFilters();render();const d=document.getElementById('clause-'+n);if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'','#clause-'+n)}}
search.addEventListener('input',render);document.getElementById('clearSearch').onclick=()=>{search.value='';render();search.focus()};document.querySelectorAll('[data-clause]').forEach(b=>b.onclick=()=>openClause(+b.dataset.clause));document.getElementById('goTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});document.getElementById('goSearch').onclick=()=>{document.getElementById('buscar').scrollIntoView({behavior:'smooth'});search.focus()};renderFilters();render();if(location.hash.startsWith('#clause-'))openClause(Number(location.hash.slice(8)));
let deferredPrompt;const installBtn=document.getElementById('installBtn'),help=document.getElementById('installHelp'),info=document.getElementById('installText');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;return}const ios=/iPhone|iPad|iPod/.test(navigator.userAgent);info.textContent=ios?'No Safari, toque em Compartilhar e depois em “Adicionar à Tela de Início”.':'No menu do navegador (⋮ ou ⋯), escolha “Instalar aplicativo” ou “Adicionar à tela inicial”. Se a opção não aparecer, aguarde a página carregar e tente novamente.';help.showModal()};window.addEventListener('appinstalled',()=>{installBtn.textContent='✓ App instalado'});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js');
